---
- fail: msg="role-python3 only supports RHEL 7 family distros"
  when: ansible_os_family == 'RedHat' and
        ansible_distribution_major_version == "6"

- import_tasks: redhat_family_7.yaml
  when: ansible_os_family == 'RedHat' and
        ansible_distribution_major_version == "7"
